let stock = [
    {name: "Instant Coffee", price: 4.00, category: "drinks", image: "../images/coffee.jpg"},
    {name: "Tea", price: 2.95, category: "drinks", image: "../images/tea.jpg"},
    {name: "Orange Juice", price: 1.75, category: "drinks", image: "../images/orangejuice.jpg"},
    {name: "Apple Juice", price: 1.60, category: "drinks", image: "../images/applejuice.jpg"},
    {name: "Milkshake", price: 2.20, category: "drinks", image: "../images/milkshake.jpg"},
    {name: "Smoothie", price: 3.50, category: "drinks", image: "../images/smoothie.jpg"},
    {name: "Apples", price: 1.50, category: "fruit&veg", image: "../images/apple.jpg"},
    {name: "Oranges", price: 1.40, category: "fruit&veg", image: "../images/oranges.jpg"},
    {name: "Pears", price: 1.60, category: "fruit&veg", image: "../images/pears.jpg"},
    {name: "Carrots", price: 0.65, category: "fruit&veg", image: "../images/carrots.jpg"},
    {name: "Onions", price: 2.00, category: "fruit&veg", image: "../images/onions.jpg"},
    {name: "Potatoes", price: 0.60, category: "fruit&veg", image: "../images/potatoes.jpg"},
    {name: "Milk", price: 0.60, category: "dairy", image: "../images/milk.jpg"},
    {name: "Yoghurt", price: 1.35, category: "dairy", image: "../images/yoghurt.jpg"},
    {name: "Cheese", price: 3.15, category: "dairy", image: "../images/cheese.jpg"},
    {name: "Eggs", price: 2.00, category: "dairy", image: "../images/eggs.jpg"},
    {name: "Butter", price: 1.80, category: "dairy", image: "../images/butter.jpg"},
    {name: "Custard", price: 1.20, category: "dairy", image: "../images/custard.jpg"},
    {name: "Crisps", price: 0.70, category: "snacks", image: "../images/crisps.jpg"},
    {name: "Chocolate", price: 1.00, category: "snacks", image: "../images/chocolate.jpg"},
    {name: "Biscuits", price: 1.20, category: "snacks", image: "../images/biscuits.jpg"},
    {name: "Sweets", price: 0.50, category: "snacks", image: "../images/sweets.jpg"},
    {name: "Cakes", price: 1.00, category: "snacks", image: "../images/cakes.jpg"},
    {name: "Raisins", price: 0.90, category: "snacks", image: "../images/raisins.jpg"},
    {name: "Chicken Breast", price: 4.00, category: "meat&fish", image: "../images/chickenbreast.jpg"},
    {name: "Minced Beef", price: 3.75, category: "meat&fish", image: "../images/mincedbeef.jpg"},
    {name: "Salmon", price: 5.00, category: "meat&fish", image: "../images/salmon.jpg"},
    {name: "Lamb", price: 4.50, category: "meat&fish", image: "../images/lamb.jpg"},
    {name: "Turkey", price: 3.70, category: "meat&fish", image: "../images/turkey.jpg"},
    {name: "Smoked haddock", price: 2.50, category: "meat&fish", image: "../images/smokedhaddock.jpg"},
    {name: "Ice cream", price: 2.00, category: "frozenfood", image: "../images/icecream.jpg"},
    {name: "Prawns", price: 3.00, category: "frozenfood", image: "../images/prawns.jpg"},
    {name: "Fish fingers", price: 2.50, category: "frozenfood", image: "../images/fishfingers.jpg"},
    {name: "Chips", price: 2.45, category: "frozenfood", image: "../images/chips.jpg"},
    {name: "Pizza", price: 3.50, category: "frozenfood", image: "../images/pizza.jpg"},
    {name: "Chicken Nuggets", price: 2.60, category: "frozenfood", image: "../images/chickennuggets.jpg"},
]


export default stock;