Main: frontend/src/availableStock.js

let stock = [
    {name: "Instant Coffee", price: 4.00, category: "drinks"},
    {name: "Tea", price: 2.95, category: "drinks"},
    {name: "Orange Juice", price: 1.75, category: "drinks"},
    {name: "Apple Juice", price: 1.60, category: "drinks"},
    {name: "Milkshake", price: 2.20, category: "drinks"},
    {name: "Smoothie", price: 3.50, category: "drinks"},
    {name: "apples", price: 1.50, category: "fruit&veg"},
    {name: "oranges", price: 1.40, category: "fruit&veg"},
    {name: "pears", price: 1.60, category: "fruit&veg"},
    {name: "carrots", price: 0.65, category: "fruit&veg"},
    {name: "onions", price: 2.00, category: "fruit&veg"},
    {name: "potatoes", price: 0.60, category: "fruit&veg"},
    {name: "milk", price: 0.60, category: "dairy"},
    {name: "yoghurt", price: 1.35, category: "dairy"},
    {name: "cheese", price: 3.15, category: "dairy"},
    {name: "eggs", price: 2.00, category: "dairy"},
    {name: "butter", price: 1.80, category: "dairy"},
    {name: "custard", price: 1.20, category: "dairy"},
    {name: "crisps", price: 0.70, category: "snacks"},
    {name: "chocolate", price: 1.00, category: "snacks"},
    {name: "biscuits", price: 1.20, category: "snacks"},
    {name: "sweets", price: 0.50, category: "snacks"},
    {name: "cakes", price: 1.00, category: "snacks"},
    {name: "raisins", price: 0.90, category: "snacks"},
    {name: "chicken breast", price: 4.00, category: "meat&fish"},
    {name: "minced beef", price: 3.75, category: "meat&fish"},
    {name: "salmon", price: 5.00, category: "meat&fish"},
    {name: "lamb", price: 4.50, category: "meat&fish"},
    {name: "turkey", price: 3.70, category: "meat&fish"},
    {name: "smoked haddock", price: 2.50, category: "meat&fish"},
    {name: "ice cream", price: 2.00, category: "frozenfood"},
    {name: "prawns", price: 3.00, category: "frozenfood"},
    {name: "fish fingers", price: 2.50, category: "frozenfood"},
    {name: "chips", price: 2.45, category: "frozenfood"},
    {name: "pizza", price: 3.50, category: "frozenfood"},
    {name: "chicken nuggets", price: 2.60, category: "frozenfood"},
]


export default stock;