let stock = [
    {name: "Instant Coffee", price: 4.00, category: "drinks"},
    {name: "Tea", price: 2.95, category: "drinks"},
    {name: "Orange Juice", price: 1.75, category: "drinks"},
    {name: "Apple Juice", price: 1.60, category: "drinks"},
    {name: "Milkshake", price: 2.20, category: "drinks"},
    {name: "Smoothie", price: 3.50, category: "drinks"},
    {name: "Apples", price: 1.50, category: "fruit&veg"},
    {name: "Oranges", price: 1.40, category: "fruit&veg"},
    {name: "Pears", price: 1.60, category: "fruit&veg"},
    {name: "Carrots", price: 0.65, category: "fruit&veg"},
    {name: "Onions", price: 2.00, category: "fruit&veg"},
    {name: "Potatoes", price: 0.60, category: "fruit&veg"},
    {name: "Milk", price: 0.60, category: "dairy"},
    {name: "Yoghurt", price: 1.35, category: "dairy"},
    {name: "Cheese", price: 3.15, category: "dairy"},
    {name: "Eggs", price: 2.00, category: "dairy"},
    {name: "Butter", price: 1.80, category: "dairy"},
    {name: "Custard", price: 1.20, category: "dairy"},
    {name: "Crisps", price: 0.70, category: "snacks"},
    {name: "Chocolate", price: 1.00, category: "snacks"},
    {name: "Biscuits", price: 1.20, category: "snacks"},
    {name: "Sweets", price: 0.50, category: "snacks"},
    {name: "Cakes", price: 1.00, category: "snacks"},
    {name: "Raisins", price: 0.90, category: "snacks"},
    {name: "Chicken Breast", price: 4.00, category: "meat&fish"},
    {name: "Minced Beef", price: 3.75, category: "meat&fish"},
    {name: "Salmon", price: 5.00, category: "meat&fish"},
    {name: "Lamb", price: 4.50, category: "meat&fish"},
    {name: "Turkey", price: 3.70, category: "meat&fish"},
    {name: "Smoked haddock", price: 2.50, category: "meat&fish"},
    {name: "Ice cream", price: 2.00, category: "frozenfood"},
    {name: "Prawns", price: 3.00, category: "frozenfood"},
    {name: "Fish fingers", price: 2.50, category: "frozenfood"},
    {name: "Chips", price: 2.45, category: "frozenfood"},
    {name: "Pizza", price: 3.50, category: "frozenfood"},
    {name: "Chicken Nuggets", price: 2.60, category: "frozenfood"},
]


export default stock;